[package]
name = "evaluator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "evaluate"
path = "evaluation.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.2", features = ["v4"] }
chrono = "0.4"
